<div class="vv_menu_button">
   <div class="colorPicker vv_grp_btn">
       <button class="vv_btn vv_dropdown_toggle" type="button" data-toggle="dropdown" tabindex="-1">
           <span class="color vv_color_swatch" style="background-color:#ffb0e2"></span>
           <span class="vv_caret_down"></span>
       </button>
       <ul class="vv_dropdown_menu vv_color_menu"><li><span colidx="100" class="vv_color_swatch" style="background-color: #f99c8d;"></span></li><li><span colidx="101" class="vv_color_swatch" style="background-color: #ffbc85;"></span></li><li><span colidx="102" class="vv_color_swatch" style="background-color: #ffe372;"></span></li><li><span colidx="103" class="vv_color_swatch" style="background-color: #fefe70;"></span></li><li><span colidx="104" class="vv_color_swatch" style="background-color: #d3fc56;"></span></li><li><span colidx="105" class="vv_color_swatch" style="background-color: #7bf778;"></span></li><li><span colidx="106" class="vv_color_swatch" style="background-color: #6afdd9;"></span></li><li><span colidx="107" class="vv_color_swatch" style="background-color: #a0b4fc;"></span></li><li><span colidx="108" class="vv_color_swatch" style="background-color: #c3a5ff;"></span></li><li><span colidx="109" class="vv_color_swatch" style="background-color: #eea0fe;"></span></li><li><span colidx="110" class="vv_color_swatch" style="background-color: #ffb0e2;"></span></li><li><span colidx="111" class="vv_color_swatch" style="background-color: #fec1be;"></span></li></ul>
    </div>
    <div class="borderPicker vv_grp_btn">
        <button class="vv_btn vv_dropdown_toggle" data-toggle="dropdown" type="button" tabindex="-1">
            <span class="border vv_pick_indicator"></span>
            <span class="vv_caret_down"></span>
        </button>
        <ul class="vv_dropdown_menu vv_border_menu"><li><span val="A1:1" class="vv_border_style vv_arrow_black"></span></li><li><span val="A1:3" class="vv_border_style vv_arrow_red"></span></li><li><span val="A1:4" class="vv_border_style vv_arrow_green"></span></li><li><span val="A1:5" class="vv_border_style vv_arrow_blue"></span></li><li><span val="A1:7" class="vv_border_style vv_arrow_purple"></span></li><li><span val="A1:6" class="vv_border_style vv_arrow_lime"></span></li><li><span val="B1:#000000:3:0:#ffffff:1:2:1:0" class="vv_border_style vv_dashed_black"></span></li><li><span val="B1:#e06060:3:0:#ffff00:1:2:1:0" class="vv_border_style vv_dashed_red"></span></li><li><span val="B1:#60e060:3:0:#ffff00:1:2:1:0" class="vv_border_style vv_dashed_lime"></span></li><li><span val="B1:#6060e0:3:0:#ffffff:1:2:1:0" class="vv_border_style vv_dashed_blue"></span></li><li><span val="B1:#e060e0:3:0:#000000:1:2:1:0" class="vv_border_style vv_dashed_purple"></span></li><li><span val="B1:#60e0e0:3:0:#000000:1:2:1:0" class="vv_border_style vv_dashed_limegreen"></span></li><li><span val="B1:#000000:3:1:#f00fff:0:2:1:0" class="vv_border_style vv_dotted_black"></span></li><li><span val="B1:#e06060:3:1:#ffffff:0:2:1:0" class="vv_border_style vv_dotted_red"></span></li><li><span val="B1:#60e060:3:1:#ffffff:0:2:1:0" class="vv_border_style vv_dotted_lime"></span></li><li><span val="B1:#6060e0:3:1:#fff000:0:2:1:0" class="vv_border_style vv_dotted_blue"></span></li><li><span val="B1:#e060e0:3:1:#0000ff:0:2:1:0" class="vv_border_style vv_dotted_purple"></span></li><li><span val="B1:#60e0e0:3:1:#0000ff:0:2:1:0" class="vv_border_style vv_dotted_limegreen"></span></li><li><span val="B1:#000000:5:0:#ffffff:0:2:1:2" class="vv_border_style vv_circle_black"></span></li><li><span val="B1:#e06060:5:0:#ffffff:0:2:1:2" class="vv_border_style vv_circle_red"></span></li><li><span val="B1:#60e060:5:0:#ff0000:0:2:1:2" class="vv_border_style vv_circle_lime"></span></li><li><span val="B1:#6060e0:5:0:#ff0000:0:2:1:2" class="vv_border_style vv_circle_blue"></span></li><li><span val="B1:#e060e0:5:0:#0000ff:0:2:1:2" class="vv_border_style vv_circle_purple"></span></li><li><span val="B1:#60e0e0:5:0:#000000:0:2:1:2" class="vv_border_style vv_circle_limegreen"></span></li><li><span val="B1:#000000:3:0:#ffffff:0:2:1:2" class="vv_border_style vv_thin_circle_black"></span></li><li><span val="B1:#e06060:3:0:#ffffff:0:2:1:2" class="vv_border_style vv_thin_circle_red"></span></li><li><span val="B1:#60e060:3:0:#ff0000:0:2:1:2" class="vv_border_style vv_thin_circle_lime"></span></li><li><span val="B1:#6060e0:3:0:#ff0000:0:2:1:2" class="vv_border_style vv_thin_circle_blue"></span></li><li><span val="B1:#e060e0:3:0:#0000ff:0:2:1:2" class="vv_border_style vv_thin_circle_purple"></span></li><li><span val="B1:#60e0e0:3:0:#000000:0:2:1:2" class="vv_border_style vv_thin_circle_limegreen"></span></li></ul>
    </div>
    <div class="textStyle vv_grp_btn">
        <button class="vv_btn vv_dropdown_toggle" data-toggle="dropdown" type="button" tabindex="-1" aria-expanded="true"><span opt="vv_icon_highlight" class="text vv_pick_indicator vv_icon_highlight"></span><span class="vv_caret_down"></span></button><div class="dropdown-backdrop"></div>
        <ul class="vv_dropdown_menu">
            <li><a opt="hightlight"><span class="vv_btn_icon vv_icon_highlight"></span>Highlight</a></li>
            <li><a opt="insert"><span class="vv_btn_icon vv_icon_insert"></span>Insert</a></li>
            <li><a opt="strike"><span class="vv_btn_icon vv_icon_strikethrough"></span>Strikethrough</a></li>
            <li><a opt="revise"><span class="vv_btn_icon vv_icon_edit"></span>Revise text</a></li>
            <li><a opt="external"><span class="vv_btn_icon vv_icon_external_link"></span>External Link</a></li>
        </ul>
    </div>
</div>